// infoq-scaffold-frontend-react-pro/src/pages/system/post/index.tsx
import {
  DeleteOutlined,
  DownloadOutlined,
  EditOutlined,
  PlusOutlined,
  ReloadOutlined,
  SearchOutlined,
} from '@ant-design/icons';
import {
  Button,
  Card,
  Col,
  Form,
  Input,
  InputNumber,
  Modal,
  Radio,
  Row,
  Select,
  Space,
  Table,
  Tooltip,
  Tree,
  TreeSelect,
} from 'antd';
import type {ColumnsType} from 'antd/es/table';
import type {DataNode} from 'antd/es/tree';
import {useCallback, useEffect, useMemo, useState} from 'react';
import type {DeptTreeVO} from '@/api/system/dept/types';
import {addPost, delPost, deptTreeSelect, getPost, listPost, updatePost,} from '@/api/system/post';
import type {PostForm, PostQuery, PostVO} from '@/api/system/post/types';
import DictTag from '@/components/DictTag';
import Pagination from '@/components/Pagination';
import RightToolbar from '@/components/RightToolbar';
import useInitialLoadEffect from '@/hooks/useInitialLoadEffect';
import useDictOptions from '@/hooks/useDictOptions';
import modal from '@/utils/modal';
import auth from '@/utils/permission';
import {download} from '@/utils/request';

const initialQuery: PostQuery = {
  pageNum: 1,
  pageSize: 10,
  deptId: '',
  belongDeptId: '',
  postCode: '',
  postName: '',
  postCategory: '',
  status: '',
};

const initialForm: PostForm = {
  postId: undefined,
  deptId: undefined,
  postCode: '',
  postName: '',
  postCategory: '',
  postSort: 0,
  status: '0',
  remark: '',
};

const toTreeData = (nodes: DeptTreeVO[]): DataNode[] =>
  nodes.map((node) => ({
    key: String(node.id),
    title: node.label,
    children: node.children?.length ? toTreeData(node.children) : undefined,
  }));

type TreeSelectOption = {
  value: string | number;
  title: string;
  children?: TreeSelectOption[];
};

const toSelectTree = (nodes: DeptTreeVO[]): TreeSelectOption[] =>
  nodes.map((node) => ({
    value: node.id,
    title: node.label,
    children: node.children?.length ? toSelectTree(node.children) : undefined,
  }));

const filterDeptTree = (nodes: DeptTreeVO[], keyword: string): DeptTreeVO[] => {
  const normalizedKeyword = keyword.trim();
  if (!normalizedKeyword) {
    return nodes;
  }

  return nodes.reduce<DeptTreeVO[]>((result, node) => {
    const children = node.children
      ? filterDeptTree(node.children, normalizedKeyword)
      : [];
    if (node.label.includes(normalizedKeyword) || children.length > 0) {
      result.push({
        ...node,
        children,
      });
    }
    return result;
  }, []);
};

const collectDeptKeys = (nodes: DeptTreeVO[]): string[] =>
  nodes.flatMap((node) => [
    String(node.id),
    ...(node.children ? collectDeptKeys(node.children) : []),
  ]);

export default function PostPage() {
  const [query, setQuery] = useState<PostQuery>(initialQuery);
  const [loading, setLoading] = useState(false);
  const [showSearch, setShowSearch] = useState(true);
  const [list, setList] = useState<PostVO[]>([]);
  const [total, setTotal] = useState(0);
  const [selectedIds, setSelectedIds] = useState<Array<string | number>>([]);
  const [deptTree, setDeptTree] = useState<DeptTreeVO[]>([]);
  const [deptName, setDeptName] = useState('');
  const [expandedDeptKeys, setExpandedDeptKeys] = useState<string[]>([]);
  const [autoExpandParent, setAutoExpandParent] = useState(false);
  const [dialogOpen, setDialogOpen] = useState(false);
  const [submitting, setSubmitting] = useState(false);
  const [form] = Form.useForm<PostForm>();
  const postId = Form.useWatch('postId', form);
  const dict = useDictOptions('sys_normal_disable');
  const filteredDeptTree = useMemo(
    () => filterDeptTree(deptTree, deptName),
    [deptName, deptTree],
  );

  const loadTree = useCallback(async () => {
    const response = await deptTreeSelect();
    setDeptTree(response.data);
  }, []);

  const loadList = useCallback(async (nextQuery: PostQuery) => {
    setLoading(true);
    try {
      const response = await listPost(nextQuery);
      setList(response.rows);
      setTotal(response.total);
    } finally {
      setLoading(false);
    }
  }, []);

  useInitialLoadEffect(() => {
    loadTree();
    loadList(initialQuery);
  }, [loadList, loadTree], {dedupeKey: 'system-post-initial-list'});

  useEffect(() => {
    setExpandedDeptKeys(collectDeptKeys(deptTree));
    setAutoExpandParent(false);
  }, [deptTree]);

  useEffect(() => {
    if (deptName.trim()) {
      setExpandedDeptKeys(collectDeptKeys(filteredDeptTree));
      setAutoExpandParent(true);
      return;
    }

    setAutoExpandParent(false);
  }, [deptName, filteredDeptTree]);

  const columns: ColumnsType<PostVO> = [
    {
      title: '岗位编码',
      dataIndex: 'postCode',
      align: 'center',
      ellipsis: true,
    },
    {
      title: '类别编码',
      dataIndex: 'postCategory',
      align: 'center',
      ellipsis: true,
    },
    {
      title: '岗位名称',
      dataIndex: 'postName',
      align: 'center',
      ellipsis: true,
    },
    { title: '部门', dataIndex: 'deptName', align: 'center', ellipsis: true },
    { title: '排序', dataIndex: 'postSort', width: 80, align: 'center' },
    {
      title: '状态',
      dataIndex: 'status',
      width: 110,
      align: 'center',
      render: (value: string) => (
        <DictTag options={dict.sys_normal_disable || []} value={value} />
      ),
    },
    { title: '创建时间', dataIndex: 'createTime', width: 180, align: 'center' },
    {
      title: '操作',
      key: 'action',
      width: 160,
      align: 'center',
      render: (_, record) => (
        <Space size={4}>
          {auth.hasPermiOr(['system:post:edit']) && (
            <Tooltip title="修改">
              <Button
                className="table-action-link"
                type="link"
                icon={<EditOutlined />}
                onClick={() => handleEdit(record.postId)}
              />
            </Tooltip>
          )}
          {auth.hasPermiOr(['system:post:remove']) && (
            <Tooltip title="删除">
              <Button
                className="table-action-link"
                type="link"
                icon={<DeleteOutlined />}
                onClick={() => handleDelete(record.postId)}
              />
            </Tooltip>
          )}
        </Space>
      ),
    },
  ];

  const handleEdit = async (postId?: string | number) => {
    if (!postId) {
      return;
    }
    const response = await getPost(postId);
    form.setFieldsValue({ ...initialForm, ...response.data });
    setDialogOpen(true);
  };

  const handleDelete = async (
    postId?: string | number | Array<string | number>,
  ) => {
    const target = postId || selectedIds;
    if (!target || (Array.isArray(target) && target.length === 0)) {
      modal.msgWarning('请选择要删除的岗位');
      return;
    }
    const confirmed = await modal.confirm(
      `是否确认删除岗位编号为 "${Array.isArray(target) ? target.join(',') : target}" 的数据项？`,
    );
    if (!confirmed) {
      return;
    }
    await delPost(target);
    modal.msgSuccess('删除成功');
    setSelectedIds([]);
    loadList(query);
  };

  const handleSubmit = async () => {
    const values = await form.validateFields();
    setSubmitting(true);
    try {
      if (values.postId) {
        await updatePost(values);
      } else {
        await addPost(values);
      }
      modal.msgSuccess('操作成功');
      setDialogOpen(false);
      loadList(query);
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <Row gutter={16}>
      <Col xs={24} xl={5}>
        <Card>
          <Input
            allowClear
            placeholder="请输入部门名称"
            value={deptName}
            onChange={(event) => setDeptName(event.target.value)}
            style={{ marginBottom: 12 }}
          />
          <Tree
            treeData={toTreeData(filteredDeptTree)}
            virtual={false}
            expandedKeys={expandedDeptKeys}
            autoExpandParent={autoExpandParent}
            onExpand={(keys) => {
              setExpandedDeptKeys(keys as string[]);
              setAutoExpandParent(false);
            }}
            onSelect={(keys) => {
              const next = {
                ...query,
                belongDeptId: keys[0] ? String(keys[0]) : '',
                deptId: '',
              };
              setQuery(next);
              loadList(next);
            }}
          />
        </Card>
      </Col>
      <Col xs={24} xl={19}>
        <Space orientation="vertical" size={12} style={{ width: '100%' }}>
          {showSearch && (
            <Card>
              <Form layout="inline" className="query-form">
                <Row gutter={16} style={{ width: '100%' }}>
                  <Col xs={24} md={12} xl={6}>
                    <Form.Item
                      label="岗位编码"
                      style={{ width: '100%', marginBottom: 12 }}
                    >
                      <Input
                        allowClear
                        placeholder="请输入岗位编码"
                        value={query.postCode}
                        onChange={(event) =>
                          setQuery((prev) => ({
                            ...prev,
                            postCode: event.target.value,
                          }))
                        }
                        onPressEnter={() => {
                          const next = { ...query, pageNum: 1 };
                          setQuery(next);
                          loadList(next);
                        }}
                      />
                    </Form.Item>
                  </Col>
                  <Col xs={24} md={12} xl={6}>
                    <Form.Item
                      label="类别编码"
                      style={{ width: '100%', marginBottom: 12 }}
                    >
                      <Input
                        allowClear
                        placeholder="请输入类别编码"
                        value={query.postCategory}
                        onChange={(event) =>
                          setQuery((prev) => ({
                            ...prev,
                            postCategory: event.target.value,
                          }))
                        }
                        onPressEnter={() => {
                          const next = { ...query, pageNum: 1 };
                          setQuery(next);
                          loadList(next);
                        }}
                      />
                    </Form.Item>
                  </Col>
                  <Col xs={24} md={12} xl={6}>
                    <Form.Item
                      label="岗位名称"
                      style={{ width: '100%', marginBottom: 12 }}
                    >
                      <Input
                        allowClear
                        placeholder="请输入岗位名称"
                        value={query.postName}
                        onChange={(event) =>
                          setQuery((prev) => ({
                            ...prev,
                            postName: event.target.value,
                          }))
                        }
                        onPressEnter={() => {
                          const next = { ...query, pageNum: 1 };
                          setQuery(next);
                          loadList(next);
                        }}
                      />
                    </Form.Item>
                  </Col>
                  <Col xs={24} md={12} xl={6}>
                    <Form.Item
                      label="部门"
                      style={{ width: '100%', marginBottom: 12 }}
                    >
                      <TreeSelect
                        allowClear
                        style={{ width: '100%' }}
                        placeholder="请选择部门"
                        value={query.deptId || undefined}
                        treeData={toSelectTree(deptTree)}
                        treeDefaultExpandAll
                        onChange={(value) =>
                          setQuery((prev) => ({
                            ...prev,
                            deptId: value as number | string,
                            belongDeptId: '',
                          }))
                        }
                      />
                    </Form.Item>
                  </Col>
                  <Col xs={24} md={12} xl={6}>
                    <Form.Item
                      label="状态"
                      style={{ width: '100%', marginBottom: 12 }}
                    >
                      <Select
                        allowClear
                        style={{ width: '100%' }}
                        placeholder="岗位状态"
                        value={query.status || undefined}
                        options={(dict.sys_normal_disable || []).map(
                          (item) => ({ label: item.label, value: item.value }),
                        )}
                        onChange={(value) =>
                          setQuery((prev) => ({ ...prev, status: value || '' }))
                        }
                      />
                    </Form.Item>
                  </Col>
                  <Col xs={24}>
                    <Form.Item style={{ marginBottom: 0 }}>
                      <Space>
                        <Button
                          type="primary"
                          icon={<SearchOutlined />}
                          onClick={() => {
                            const next = { ...query, pageNum: 1 };
                            setQuery(next);
                            loadList(next);
                          }}
                        >
                          搜索
                        </Button>
                        <Button
                          icon={<ReloadOutlined />}
                          onClick={() => {
                            setQuery(initialQuery);
                            loadList(initialQuery);
                          }}
                        >
                          重置
                        </Button>
                      </Space>
                    </Form.Item>
                  </Col>
                </Row>
              </Form>
            </Card>
          )}

          <Card>
            <div className="table-toolbar">
              <Space wrap className="toolbar-buttons">
                {auth.hasPermiOr(['system:post:add']) && (
                  <Button
                    className="btn-plain-primary"
                    icon={<PlusOutlined />}
                    onClick={() => {
                      form.setFieldsValue(initialForm);
                      setDialogOpen(true);
                    }}
                  >
                    新增
                  </Button>
                )}
                {auth.hasPermiOr(['system:post:edit']) && (
                  <Button
                    className="btn-plain-success"
                    icon={<EditOutlined />}
                    onClick={() => handleEdit(selectedIds[0])}
                    disabled={selectedIds.length !== 1}
                  >
                    修改
                  </Button>
                )}
                {auth.hasPermiOr(['system:post:remove']) && (
                  <Button
                    className="btn-plain-danger"
                    icon={<DeleteOutlined />}
                    onClick={() => handleDelete()}
                    disabled={selectedIds.length === 0}
                  >
                    删除
                  </Button>
                )}
                {auth.hasPermiOr(['system:post:export']) && (
                  <Button
                    className="btn-plain-warning"
                    icon={<DownloadOutlined />}
                    onClick={() =>
                      download(
                        '/system/post/export',
                        { ...query },
                        `post_${Date.now()}.xlsx`,
                      )
                    }
                  >
                    导出
                  </Button>
                )}
              </Space>
              <div className="right-toolbar-wrap">
                <RightToolbar
                  showSearch={showSearch}
                  onShowSearchChange={setShowSearch}
                  onQueryTable={() => loadList(query)}
                />
              </div>
            </div>

            <Table<PostVO>
              rowKey="postId"
              loading={loading}
              bordered
              columns={columns}
              dataSource={list}
              pagination={false}
              rowSelection={{
                selectedRowKeys: selectedIds,
                onChange: (keys) =>
                  setSelectedIds(keys as Array<string | number>),
              }}
            />

            <Pagination
              total={total}
              page={query.pageNum}
              limit={query.pageSize}
              onPageChange={({ page, limit }) => {
                const next = { ...query, pageNum: page, pageSize: limit };
                setQuery(next);
                loadList(next);
              }}
            />
          </Card>
        </Space>
      </Col>

      <Modal
        open={dialogOpen}
        title={postId ? '修改岗位' : '新增岗位'}
        confirmLoading={submitting}
        onCancel={() => setDialogOpen(false)}
        onOk={handleSubmit}
      >
        <Form form={form} layout="vertical" initialValues={initialForm}>
          <Form.Item
            label="岗位名称"
            name="postName"
            rules={[{ required: true, message: '岗位名称不能为空' }]}
          >
            <Input />
          </Form.Item>
          <Form.Item
            label="部门"
            name="deptId"
            rules={[{ required: true, message: '部门不能为空' }]}
          >
            <TreeSelect
              treeData={toSelectTree(deptTree)}
              placeholder="请选择部门"
              allowClear
              treeDefaultExpandAll
            />
          </Form.Item>
          <Form.Item
            label="岗位编码"
            name="postCode"
            rules={[{ required: true, message: '岗位编码不能为空' }]}
          >
            <Input />
          </Form.Item>
          <Form.Item label="类别编码" name="postCategory">
            <Input />
          </Form.Item>
          <Form.Item
            label="岗位顺序"
            name="postSort"
            rules={[{ required: true, message: '岗位顺序不能为空' }]}
          >
            <InputNumber min={0} style={{ width: '100%' }} />
          </Form.Item>
          <Form.Item label="岗位状态" name="status">
            <Radio.Group
              options={(dict.sys_normal_disable || []).map((item) => ({
                label: item.label,
                value: item.value,
              }))}
            />
          </Form.Item>
          <Form.Item label="备注" name="remark">
            <Input.TextArea rows={4} />
          </Form.Item>
        </Form>
      </Modal>
    </Row>
  );
}

// infoq-scaffold-frontend-vue/src/views/system/post/index.vue
<template>
  <div class="p-2">
    <el-row :gutter="20">
      <!-- 部门树 -->
      <el-col :lg="4" :xs="24" style="">
        <el-card shadow="hover">
          <el-input v-model="deptName" placeholder="请输入部门名称" prefix-icon="Search" clearable />
          <el-tree
            ref="deptTreeRef"
            class="mt-2"
            node-key="id"
            :data="deptOptions"
            :props="deptTreeProps"
            :expand-on-click-node="false"
            :filter-node-method="filterNode"
            highlight-current
            default-expand-all
            @node-click="handleNodeClick"
          />
        </el-card>
      </el-col>
      <el-col :lg="20" :xs="24">
        <transition :enter-active-class="proxy?.animate.searchAnimate.enter" :leave-active-class="proxy?.animate.searchAnimate.leave">
          <div v-show="showSearch" class="mb-[10px]">
            <el-card shadow="hover">
              <el-form ref="queryFormRef" :model="queryParams" :inline="true">
                <el-form-item label="岗位编码" prop="postCode">
                  <el-input v-model="queryParams.postCode" placeholder="请输入岗位编码" clearable @keyup.enter="handleQuery" />
                </el-form-item>
                <el-form-item label="类别编码" prop="postCategory">
                  <el-input
                    v-model="queryParams.postCategory"
                    placeholder="请输入类别编码"
                    clearable
                    style="width: 200px"
                    @keyup.enter="handleQuery"
                  />
                </el-form-item>
                <el-form-item label="岗位名称" prop="postName">
                  <el-input v-model="queryParams.postName" placeholder="请输入岗位名称" clearable @keyup.enter="handleQuery" />
                </el-form-item>
                <el-form-item label="部门" prop="deptId">
                  <el-tree-select
                    v-model="queryParams.deptId"
                    :data="deptOptions"
                    :props="deptSelectProps"
                    value-key="id"
                    placeholder="请选择部门"
                    check-strictly
                  />
                </el-form-item>
                <el-form-item label="状态" prop="status">
                  <el-select v-model="queryParams.status" placeholder="岗位状态" clearable>
                    <el-option v-for="dict in sys_normal_disable" :key="dict.value" :label="dict.label" :value="dict.value" />
                  </el-select>
                </el-form-item>
                <el-form-item>
                  <el-button type="primary" icon="Search" @click="handleQuery">搜索</el-button>
                  <el-button icon="Refresh" @click="resetQuery">重置</el-button>
                </el-form-item>
              </el-form>
            </el-card>
          </div>
        </transition>
        <el-card shadow="hover">
          <template #header>
            <el-row :gutter="10" class="mb8">
              <el-col :span="1.5">
                <el-button v-hasPermi="['system:post:add']" type="primary" plain icon="Plus" @click="handleAdd">新增</el-button>
              </el-col>
              <el-col :span="1.5">
                <el-button v-hasPermi="['system:post:edit']" type="success" plain icon="Edit" :disabled="single" @click="handleUpdate()"
                  >修改</el-button
                >
              </el-col>
              <el-col :span="1.5">
                <el-button v-hasPermi="['system:post:remove']" type="danger" plain icon="Delete" :disabled="multiple" @click="handleDelete()">
                  删除
                </el-button>
              </el-col>
              <el-col :span="1.5">
                <el-button v-hasPermi="['system:post:export']" type="warning" plain icon="Download" @click="handleExport">导出</el-button>
              </el-col>
              <right-toolbar v-model:show-search="showSearch" @query-table="getList"></right-toolbar>
            </el-row>
          </template>
          <el-table v-loading="loading" border :data="postList" @selection-change="handleSelectionChange">
            <el-table-column type="selection" width="55" align="center" />
            <el-table-column label="岗位编码" align="center" prop="postCode" />
            <el-table-column label="类别编码" align="center" prop="postCategory" />
            <el-table-column label="岗位名称" align="center" prop="postName" />
            <el-table-column label="部门" align="center" prop="deptName" />
            <el-table-column label="排序" align="center" prop="postSort" />
            <el-table-column label="状态" align="center" prop="status">
              <template #default="scope">
                <dict-tag :options="sys_normal_disable" :value="scope.row.status" />
              </template>
            </el-table-column>
            <el-table-column label="创建时间" align="center" prop="createTime" width="180">
              <template #default="scope">
                <span>{{ proxy.parseTime(scope.row.createTime) }}</span>
              </template>
            </el-table-column>
            <el-table-column label="操作" width="180" align="center" class-name="small-padding fixed-width">
              <template #default="scope">
                <el-tooltip content="修改" placement="top">
                  <el-button v-hasPermi="['system:post:edit']" link type="primary" icon="Edit" @click="handleUpdate(scope.row)"></el-button>
                </el-tooltip>
                <el-tooltip content="删除" placement="top">
                  <el-button v-hasPermi="['system:post:remove']" link type="primary" icon="Delete" @click="handleDelete(scope.row)"></el-button>
                </el-tooltip>
              </template>
            </el-table-column>
          </el-table>

          <pagination
            v-show="total > 0"
            v-model:page="queryParams.pageNum"
            v-model:limit="queryParams.pageSize"
            :total="total"
            @pagination="getList"
          />
        </el-card>

        <!-- 添加或修改岗位对话框 -->
        <el-dialog v-model="dialog.visible" :title="dialog.title" width="500px" append-to-body>
          <el-form ref="postFormRef" :model="form" :rules="rules" label-width="80px">
            <el-form-item label="岗位名称" prop="postName">
              <el-input v-model="form.postName" placeholder="请输入岗位名称" />
            </el-form-item>
            <el-form-item label="部门" prop="deptId">
              <el-tree-select
                v-model="form.deptId"
                :data="deptOptions"
                :props="deptSelectProps"
                value-key="id"
                placeholder="请选择部门"
                check-strictly
              />
            </el-form-item>
            <el-form-item label="岗位编码" prop="postCode">
              <el-input v-model="form.postCode" placeholder="请输入编码名称" />
            </el-form-item>
            <el-form-item label="类别编码" prop="postCategory">
              <el-input v-model="form.postCategory" placeholder="请输入类别编码" />
            </el-form-item>
            <el-form-item label="岗位顺序" prop="postSort">
              <el-input-number v-model="form.postSort" controls-position="right" :min="0" />
            </el-form-item>
            <el-form-item label="岗位状态" prop="status">
              <el-radio-group v-model="form.status">
                <el-radio v-for="dict in sys_normal_disable" :key="dict.value" :value="dict.value">{{ dict.label }}</el-radio>
              </el-radio-group>
            </el-form-item>
            <el-form-item label="备注" prop="remark">
              <el-input v-model="form.remark" type="textarea" placeholder="请输入内容" />
            </el-form-item>
          </el-form>
          <template #footer>
            <div class="dialog-footer">
              <el-button type="primary" @click="submitForm">确 定</el-button>
              <el-button @click="cancel">取 消</el-button>
            </div>
          </template>
        </el-dialog>
      </el-col>
    </el-row>
  </div>
</template>

<script setup name="Post" lang="ts">
import { addPost, delPost, deptTreeSelect, getPost, listPost, updatePost } from '@/api/system/post';
import { PostForm, PostQuery, PostVO } from '@/api/system/post/types';
import { DeptTreeVO, DeptVO } from '@/api/system/dept/types';
import { toDictRefs } from '@/utils/dict';

const { proxy } = getCurrentInstance() as ComponentInternalInstance;
const { sys_normal_disable } = toDictRefs((proxy?.useDict('sys_normal_disable') ?? {}) as Record<'sys_normal_disable', DictDataOption[]>);

const postList = ref<PostVO[]>([]);
const loading = ref(true);
const showSearch = ref(true);
const ids = ref<Array<number | string>>([]);
const single = ref(true);
const multiple = ref(true);
const total = ref(0);
const deptName = ref('');
const deptOptions = ref<DeptTreeVO[]>([]);
const deptTreeRef = ref<ElTreeInstance>();
const postFormRef = ref<ElFormInstance>();
const queryFormRef = ref<ElFormInstance>();
const deptTreeProps = { label: 'label', children: 'children' } as const;
const deptSelectProps = { value: 'id', label: 'label', children: 'children' } as const;

const dialog = reactive<DialogOption>({
  visible: false,
  title: ''
});

const initFormData: PostForm = {
  postId: undefined,
  deptId: undefined,
  postCode: '',
  postName: '',
  postCategory: '',
  postSort: 0,
  status: '0',
  remark: ''
};

const data = reactive<PageData<PostForm, PostQuery>>({
  form: { ...initFormData },
  queryParams: {
    pageNum: 1,
    pageSize: 10,
    deptId: undefined,
    belongDeptId: undefined,
    postCode: '',
    postName: '',
    postCategory: '',
    status: ''
  },
  rules: {
    postName: [{ required: true, message: '岗位名称不能为空', trigger: 'blur' }],
    postCode: [{ required: true, message: '岗位编码不能为空', trigger: 'blur' }],
    deptId: [{ required: true, message: '部门不能为空', trigger: 'blur' }],
    postSort: [{ required: true, message: '岗位顺序不能为空', trigger: 'blur' }]
  }
});

const { queryParams, form, rules } = toRefs<PageData<PostForm, PostQuery>>(data);

/** 通过条件过滤节点  */
const filterNode = (value: string, data: { label: string }) => {
  if (!value) return true;
  return data.label.indexOf(value) !== -1;
};

/** 根据名称筛选部门树 */
watchEffect(
  () => {
    deptTreeRef.value?.filter(deptName.value);
  },
  {
    flush: 'post' // watchEffect会在DOM挂载或者更新之前就会触发，此属性控制在DOM元素更新后运行
  }
);

/** 查询部门下拉树结构 */
const getTreeSelect = async () => {
  const res = await deptTreeSelect();
  deptOptions.value = res.data;
};

/** 节点单击事件 */
const handleNodeClick = (data: DeptVO) => {
  queryParams.value.belongDeptId = data.id;
  queryParams.value.deptId = undefined;
  handleQuery();
};

/** 查询岗位列表 */
const getList = async () => {
  loading.value = true;
  const res = await listPost(queryParams.value);
  postList.value = res.rows;
  total.value = res.total;
  loading.value = false;
};

/** 取消按钮 */
const cancel = () => {
  reset();
  dialog.visible = false;
};

/** 表单重置 */
const reset = () => {
  form.value = { ...initFormData };
  postFormRef.value?.resetFields();
};

/** 搜索按钮操作 */
const handleQuery = () => {
  queryParams.value.pageNum = 1;
  if (queryParams.value.deptId) {
    queryParams.value.belongDeptId = undefined;
  }
  getList();
};

/** 重置按钮操作 */
const resetQuery = () => {
  queryFormRef.value?.resetFields();
  queryParams.value.pageNum = 1;
  queryParams.value.deptId = undefined;
  deptTreeRef.value?.setCurrentKey(undefined);
  /** 清空左边部门树选中值 */
  queryParams.value.belongDeptId = undefined;
  handleQuery();
};

/** 多选框选中数据 */
const handleSelectionChange = (selection: PostVO[]) => {
  ids.value = selection.map((item) => item.postId);
  single.value = selection.length != 1;
  multiple.value = !selection.length;
};

/** 新增按钮操作 */
const handleAdd = () => {
  reset();
  dialog.visible = true;
  dialog.title = '添加岗位';
};

/** 修改按钮操作 */
const handleUpdate = async (row?: PostVO) => {
  reset();
  const postId = row?.postId || ids.value[0];
  const res = await getPost(postId);
  Object.assign(form.value, res.data);
  dialog.visible = true;
  dialog.title = '修改岗位';
};

/** 提交按钮 */
const submitForm = () => {
  postFormRef.value?.validate(async (valid: boolean) => {
    if (valid) {
      const payload: PostForm = {
        postId: form.value.postId,
        deptId: form.value.deptId,
        postCode: form.value.postCode,
        postName: form.value.postName,
        postCategory: form.value.postCategory,
        postSort: form.value.postSort,
        status: form.value.status,
        remark: form.value.remark
      };
      payload.postId ? await updatePost(payload) : await addPost(payload);
      proxy?.$modal.msgSuccess('操作成功');
      dialog.visible = false;
      await getList();
    }
  });
};

/** 删除按钮操作 */
const handleDelete = async (row?: PostVO) => {
  const postIds = row?.postId || ids.value;
  await proxy?.$modal.confirm('是否确认删除岗位编号为"' + postIds + '"的数据项？');
  await delPost(postIds);
  await getList();
  proxy?.$modal.msgSuccess('删除成功');
};

/** 导出按钮操作 */
const handleExport = () => {
  proxy?.download(
    'system/post/export',
    {
      ...queryParams.value
    },
    `post_${new Date().getTime()}.xlsx`
  );
};

onMounted(() => {
  getTreeSelect(); // 初始化部门数据
  getList();
});
</script>
