// infoq-scaffold-frontend-vue/src/views/system/role/index.vue
<template>
  <div class="p-2">
    <transition :enter-active-class="proxy?.animate.searchAnimate.enter" :leave-active-class="proxy?.animate.searchAnimate.leave">
      <div v-show="showSearch" class="mb-[10px]">
        <el-card shadow="hover">
          <el-form ref="queryFormRef" :model="queryParams" :inline="true">
            <el-form-item label="角色名称" prop="roleName">
              <el-input v-model="queryParams.roleName" placeholder="请输入角色名称" clearable @keyup.enter="handleQuery" />
            </el-form-item>
            <el-form-item label="权限字符" prop="roleKey">
              <el-input v-model="queryParams.roleKey" placeholder="请输入权限字符" clearable @keyup.enter="handleQuery" />
            </el-form-item>
            <el-form-item label="状态" prop="status">
              <el-select v-model="queryParams.status" placeholder="角色状态" clearable>
                <el-option v-for="dict in sys_normal_disable" :key="dict.value" :label="dict.label" :value="dict.value" />
              </el-select>
            </el-form-item>
            <el-form-item label="创建时间" style="width: 308px">
              <el-date-picker
                v-model="dateRange"
                value-format="YYYY-MM-DD HH:mm:ss"
                type="daterange"
                range-separator="-"
                start-placeholder="开始日期"
                end-placeholder="结束日期"
                :default-time="[new Date(2000, 1, 1, 0, 0, 0), new Date(2000, 1, 1, 23, 59, 59)]"
              ></el-date-picker>
            </el-form-item>

            <el-form-item>
              <el-button type="primary" icon="Search" @click="handleQuery">搜索</el-button>
              <el-button icon="Refresh" @click="resetQuery">重置</el-button>
            </el-form-item>
          </el-form>
        </el-card>
      </div>
    </transition>

    <el-card shadow="hover">
      <template #header>
        <el-row :gutter="10">
          <el-col :span="1.5">
            <el-button v-hasPermi="['system:role:add']" type="primary" plain icon="Plus" @click="handleAdd()">新增</el-button>
          </el-col>
          <el-col :span="1.5">
            <el-button v-hasPermi="['system:role:edit']" type="success" plain :disabled="single" icon="Edit" @click="handleUpdate()">修改</el-button>
          </el-col>
          <el-col :span="1.5">
            <el-button v-hasPermi="['system:role:remove']" type="danger" plain :disabled="ids.length === 0" @click="handleDelete()">删除</el-button>
          </el-col>
          <el-col :span="1.5">
            <el-button v-hasPermi="['system:role:export']" type="warning" plain icon="Download" @click="handleExport">导出</el-button>
          </el-col>
          <right-toolbar v-model:show-search="showSearch" @query-table="getList"></right-toolbar>
        </el-row>
      </template>

      <el-table ref="roleTableRef" border v-loading="loading" :data="roleList" @selection-change="handleSelectionChange">
        <el-table-column type="selection" width="55" align="center" />
        <el-table-column label="角色名称" prop="roleName" :show-overflow-tooltip="true" width="150" />
        <el-table-column label="权限字符" prop="roleKey" :show-overflow-tooltip="true" width="200" />
        <el-table-column label="显示顺序" prop="roleSort" width="100" />
        <el-table-column label="状态" align="center" width="100">
          <template #default="scope">
            <el-switch v-model="scope.row.status" active-value="0" inactive-value="1" @change="handleStatusChange(scope.row)"></el-switch>
          </template>
        </el-table-column>
        <el-table-column label="创建时间" align="center" prop="createTime">
          <template #default="scope">
            <span>{{ proxy.parseTime(scope.row.createTime) }}</span>
          </template>
        </el-table-column>

        <el-table-column fixed="right" label="操作" width="180">
          <template #default="scope">
            <el-tooltip v-if="scope.row.roleId !== 1" content="修改" placement="top">
              <el-button v-hasPermi="['system:role:edit']" link type="primary" icon="Edit" @click="handleUpdate(scope.row)"></el-button>
            </el-tooltip>
            <el-tooltip v-if="scope.row.roleId !== 1" content="删除" placement="top">
              <el-button v-hasPermi="['system:role:remove']" link type="primary" icon="Delete" @click="handleDelete(scope.row)"></el-button>
            </el-tooltip>
            <el-tooltip v-if="scope.row.roleId !== 1" content="数据权限" placement="top">
              <el-button v-hasPermi="['system:role:edit']" link type="primary" icon="CircleCheck" @click="handleDataScope(scope.row)"></el-button>
            </el-tooltip>
            <el-tooltip v-if="scope.row.roleId !== 1" content="分配用户" placement="top">
              <el-button v-hasPermi="['system:role:edit']" link type="primary" icon="User" @click="handleAuthUser(scope.row)"></el-button>
            </el-tooltip>
          </template>
        </el-table-column>
      </el-table>

      <pagination
        v-if="total > 0"
        v-model:total="total"
        v-model:page="queryParams.pageNum"
        v-model:limit="queryParams.pageSize"
        @pagination="getList"
      />
    </el-card>

    <el-dialog v-model="dialog.visible" :title="dialog.title" width="500px" append-to-body>
      <el-form ref="roleFormRef" :model="form" :rules="rules" label-width="100px">
        <el-form-item label="角色名称" prop="roleName">
          <el-input v-model="form.roleName" placeholder="请输入角色名称" />
        </el-form-item>
        <el-form-item prop="roleKey">
          <template #label>
            <span>
              <el-tooltip content="控制器中定义的权限字符，如：@SaCheckRole('admin')" placement="top">
                <el-icon><question-filled /></el-icon>
              </el-tooltip>
              权限字符
            </span>
          </template>
          <el-input v-model="form.roleKey" placeholder="请输入权限字符" />
        </el-form-item>
        <el-form-item label="角色顺序" prop="roleSort">
          <el-input-number v-model="form.roleSort" controls-position="right" :min="0" />
        </el-form-item>
        <el-form-item label="状态">
          <el-radio-group v-model="form.status">
            <el-radio v-for="dict in sys_normal_disable" :key="dict.value" :value="dict.value">{{ dict.label }}</el-radio>
          </el-radio-group>
        </el-form-item>
        <el-form-item label="菜单权限">
          <el-checkbox v-model="menuExpand" @change="handleCheckedTreeExpand($event, 'menu')">展开/折叠</el-checkbox>
          <el-checkbox v-model="menuNodeAll" @change="handleCheckedTreeNodeAll($event, 'menu')">全选/全不选</el-checkbox>
          <el-checkbox v-model="form.menuCheckStrictly" @change="handleCheckedTreeConnect($event, 'menu')">父子联动</el-checkbox>
          <el-tree
            ref="menuRef"
            class="tree-border"
            :data="menuOptions"
            show-checkbox
            node-key="id"
            :check-strictly="!form.menuCheckStrictly"
            empty-text="加载中，请稍候"
            :props="treeProps"
          ></el-tree>
        </el-form-item>
        <el-form-item label="备注">
          <el-input v-model="form.remark" type="textarea" placeholder="请输入内容"></el-input>
        </el-form-item>
      </el-form>
      <template #footer>
        <div class="dialog-footer">
          <el-button type="primary" @click="submitForm">确 定</el-button>
          <el-button @click="cancel">取 消</el-button>
        </div>
      </template>
    </el-dialog>

    <!-- 分配角色数据权限对话框 -->
    <el-dialog v-model="openDataScope" :title="dialog.title" width="500px" append-to-body>
      <el-form ref="dataScopeRef" :model="form" label-width="80px">
        <el-form-item label="角色名称">
          <el-input v-model="form.roleName" :disabled="true" />
        </el-form-item>
        <el-form-item label="权限字符">
          <el-input v-model="form.roleKey" :disabled="true" />
        </el-form-item>
        <el-form-item label="权限范围">
          <el-select v-model="form.dataScope" @change="dataScopeSelectChange">
            <el-option v-for="item in dataScopeOptions" :key="item.value" :label="item.label" :value="item.value"></el-option>
          </el-select>
        </el-form-item>
        <el-form-item v-show="form.dataScope === '2'" label="数据权限">
          <el-checkbox v-model="deptExpand" @change="handleCheckedTreeExpand($event, 'dept')">展开/折叠</el-checkbox>
          <el-checkbox v-model="deptNodeAll" @change="handleCheckedTreeNodeAll($event, 'dept')">全选/全不选</el-checkbox>
          <el-checkbox v-model="form.deptCheckStrictly" @change="handleCheckedTreeConnect($event, 'dept')">父子联动</el-checkbox>
          <el-tree
            ref="deptRef"
            class="tree-border"
            :data="deptOptions"
            show-checkbox
            default-expand-all
            node-key="id"
            :check-strictly="!form.deptCheckStrictly"
            empty-text="加载中，请稍候"
            :props="treeProps"
          ></el-tree>
        </el-form-item>
      </el-form>
      <template #footer>
        <div class="dialog-footer">
          <el-button type="primary" @click="submitDataScope">确 定</el-button>
          <el-button @click="cancelDataScope">取 消</el-button>
        </div>
      </template>
    </el-dialog>
  </div>
</template>

<script setup name="Role" lang="ts">
import { addRole, changeRoleStatus, dataScope, delRole, deptTreeSelect, getRole, listRole, updateRole } from '@/api/system/role';
import { roleMenuTreeselect, treeselect as menuTreeselect } from '@/api/system/menu/index';
import { DeptTreeOption, RoleForm, RoleQuery, RoleVO } from '@/api/system/role/types';
import { MenuTreeOption, RoleMenuTree } from '@/api/system/menu/types';
import { toDictRefs } from '@/utils/dict';

const router = useRouter();
const { proxy } = getCurrentInstance() as ComponentInternalInstance;
const { sys_normal_disable } = toDictRefs((proxy?.useDict('sys_normal_disable') ?? {}) as Record<'sys_normal_disable', DictDataOption[]>);

const roleList = ref<RoleVO[]>();
const loading = ref(true);
const showSearch = ref(true);
const ids = ref<Array<string | number>>([]);
const single = ref(true);
const multiple = ref(true);
const total = ref(0);
const dateRange = ref<[DateModelType, DateModelType]>(['', '']);
const menuOptions = ref<MenuTreeOption[]>([]);
const menuExpand = ref(false);
const menuNodeAll = ref(false);
const deptExpand = ref(true);
const deptNodeAll = ref(false);
const deptOptions = ref<DeptTreeOption[]>([]);
const openDataScope = ref(false);

/** 数据范围选项*/
const dataScopeOptions = ref([
  { value: '1', label: '全部数据权限' },
  { value: '2', label: '自定数据权限' },
  { value: '3', label: '本部门数据权限' },
  { value: '4', label: '本部门及以下数据权限' },
  { value: '5', label: '仅本人数据权限' },
  { value: '6', label: '部门及以下或本人数据权限' }
]);

const queryFormRef = ref<ElFormInstance>();
const roleFormRef = ref<ElFormInstance>();
const dataScopeRef = ref<ElFormInstance>();
const menuRef = ref<ElTreeInstance>();
const deptRef = ref<ElTreeInstance>();
const treeProps = { label: 'label', children: 'children' } as const;

const initForm: RoleForm = {
  roleId: undefined,
  roleSort: 1,
  status: '0',
  roleName: '',
  roleKey: '',
  menuCheckStrictly: true,
  deptCheckStrictly: true,
  remark: '',
  dataScope: '1',
  menuIds: [],
  deptIds: []
};

const data = reactive<PageData<RoleForm, RoleQuery>>({
  form: { ...initForm },
  queryParams: {
    pageNum: 1,
    pageSize: 10,
    roleName: '',
    roleKey: '',
    status: ''
  },
  rules: {
    roleName: [{ required: true, message: '角色名称不能为空', trigger: 'blur' }],
    roleKey: [{ required: true, message: '权限字符不能为空', trigger: 'blur' }],
    roleSort: [{ required: true, message: '角色顺序不能为空', trigger: 'blur' }]
  }
});
const { form, queryParams, rules } = toRefs(data);

const dialog = reactive<DialogOption>({
  visible: false,
  title: ''
});

/**
 * 查询角色列表
 */
const getList = () => {
  loading.value = true;
  listRole(proxy?.addDateRange(queryParams.value, dateRange.value)).then((res) => {
    roleList.value = res.rows;
    total.value = res.total;
    loading.value = false;
  });
};

/**
 * 搜索按钮操作
 */
const handleQuery = () => {
  queryParams.value.pageNum = 1;
  getList();
};

/** 重置 */
const resetQuery = () => {
  dateRange.value = ['', ''];
  queryFormRef.value?.resetFields();
  handleQuery();
};
/**删除按钮操作 */
const handleDelete = async (row?: RoleVO) => {
  const roleids = row?.roleId || ids.value;
  await proxy?.$modal.confirm('是否确认删除角色编号为' + roleids + '数据项目');
  await delRole(roleids);
  getList();
  proxy?.$modal.msgSuccess('删除成功');
};

/** 导出按钮操作 */
const handleExport = () => {
  proxy?.download(
    'system/role/export',
    {
      ...queryParams.value
    },
    `role_${new Date().getTime()}.xlsx`
  );
};
/** 多选框选中数据 */
const handleSelectionChange = (selection: RoleVO[]) => {
  ids.value = selection.map((item: RoleVO) => item.roleId);
  single.value = selection.length != 1;
  multiple.value = !selection.length;
};

/** 角色状态修改 */
const handleStatusChange = async (row: RoleVO) => {
  const text = row.status === '0' ? '启用' : '停用';
  try {
    await proxy?.$modal.confirm('确认要"' + text + '""' + row.roleName + '"角色吗?');
    await changeRoleStatus(row.roleId, row.status);
    proxy?.$modal.msgSuccess(text + '成功');
  } catch {
    row.status = row.status === '0' ? '1' : '0';
  }
};

/** 分配用户 */
const handleAuthUser = (row: RoleVO) => {
  router.push('/system/role-auth/user/' + row.roleId);
};

/** 查询菜单树结构 */
const getMenuTreeselect = async () => {
  const res = await menuTreeselect();
  menuOptions.value = res.data;
};
/** 所有部门节点数据 */
const getDeptAllCheckedKeys = (): Array<string | number> => {
  const checkedKeys = deptRef.value?.getCheckedKeys() || [];
  const halfCheckedKeys = deptRef.value?.getHalfCheckedKeys() || [];
  return [...new Set([...checkedKeys, ...halfCheckedKeys])];
};
/** 重置新增的表单以及其他数据  */
const reset = () => {
  menuRef.value?.setCheckedKeys([]);
  menuExpand.value = false;
  menuNodeAll.value = false;
  deptExpand.value = true;
  deptNodeAll.value = false;
  form.value = { ...initForm };
  roleFormRef.value?.resetFields();
};

/** 添加角色 */
const handleAdd = () => {
  reset();
  getMenuTreeselect();
  dialog.visible = true;
  dialog.title = '添加角色';
};
/** 修改角色 */
const handleUpdate = async (row?: RoleVO) => {
  reset();
  const roleId = row?.roleId || ids.value[0];
  const { data } = await getRole(roleId);
  Object.assign(form.value, data);
  form.value.roleSort = Number(form.value.roleSort);
  const res = await getRoleMenuTreeselect(roleId);
  dialog.title = '修改角色';
  dialog.visible = true;
  res.checkedKeys.forEach((v) => {
    nextTick(() => {
      menuRef.value?.setChecked(v, true, false);
    });
  });
};
/** 根据角色ID查询菜单树结构 */
const getRoleMenuTreeselect = (roleId: string | number) => {
  return roleMenuTreeselect(roleId).then((res): RoleMenuTree => {
    menuOptions.value = res.data.menus;
    return res.data;
  });
};
/** 根据角色ID查询部门树结构 */
const getRoleDeptTreeSelect = async (roleId: string | number) => {
  const res = await deptTreeSelect(roleId);
  deptOptions.value = res.data.depts;
  return res.data;
};
/** 树权限（展开/折叠）*/
const handleCheckedTreeExpand = (value: boolean, type: string) => {
  if (type == 'menu') {
    const treeList = menuOptions.value;
    for (let i = 0; i < treeList.length; i++) {
      if (menuRef.value) {
        menuRef.value.store.nodesMap[treeList[i].id].expanded = value;
      }
    }
  } else if (type == 'dept') {
    const treeList = deptOptions.value;
    for (let i = 0; i < treeList.length; i++) {
      if (deptRef.value) {
        deptRef.value.store.nodesMap[treeList[i].id].expanded = value;
      }
    }
  }
};
/** 树权限（全选/全不选） */
const handleCheckedTreeNodeAll = (value: boolean, type: string) => {
  if (type == 'menu') {
    menuRef.value?.setCheckedNodes(value ? menuOptions.value : []);
  } else if (type == 'dept') {
    deptRef.value?.setCheckedNodes(value ? deptOptions.value : []);
  }
};
/** 树权限（父子联动） */
const handleCheckedTreeConnect = (value: boolean, type: string) => {
  if (type == 'menu') {
    form.value.menuCheckStrictly = value;
  } else if (type == 'dept') {
    form.value.deptCheckStrictly = value;
  }
};
/** 所有菜单节点数据 */
const getMenuAllCheckedKeys = (): Array<string | number> => {
  const checkedKeys = menuRef.value?.getCheckedKeys() || [];
  const halfCheckedKeys = menuRef.value?.getHalfCheckedKeys() || [];
  return [...new Set([...checkedKeys, ...halfCheckedKeys])];
};
/** 提交按钮 */
const submitForm = () => {
  roleFormRef.value?.validate(async (valid: boolean) => {
    if (valid) {
      const payload: RoleForm = {
        roleId: form.value.roleId,
        roleName: form.value.roleName,
        roleKey: form.value.roleKey,
        roleSort: form.value.roleSort,
        status: form.value.status,
        menuCheckStrictly: form.value.menuCheckStrictly,
        deptCheckStrictly: form.value.deptCheckStrictly,
        remark: form.value.remark,
        dataScope: form.value.dataScope,
        menuIds: getMenuAllCheckedKeys(),
        deptIds: form.value.deptIds
      };
      payload.roleId ? await updateRole(payload) : await addRole(payload);
      proxy?.$modal.msgSuccess('操作成功');
      dialog.visible = false;
      getList();
    }
  });
};
/** 取消按钮 */
const cancel = () => {
  reset();
  dialog.visible = false;
};
/** 选择角色权限范围触发 */
const dataScopeSelectChange = (value: string) => {
  if (value !== '2') {
    deptRef.value?.setCheckedKeys([]);
  }
};
/** 分配数据权限操作 */
const handleDataScope = async (row: RoleVO) => {
  const response = await getRole(row.roleId);
  Object.assign(form.value, response.data);
  const res = await getRoleDeptTreeSelect(row.roleId);
  openDataScope.value = true;
  dialog.title = '分配数据权限';
  await nextTick(() => {
    deptRef.value?.setCheckedKeys(res.checkedKeys);
  });
};
/** 提交按钮（数据权限） */
const submitDataScope = async () => {
  if (form.value.roleId) {
    form.value.deptIds = getDeptAllCheckedKeys();
    await dataScope(form.value);
    proxy?.$modal.msgSuccess('修改成功');
    openDataScope.value = false;
    getList();
  }
};
/** 取消按钮（数据权限）*/
const cancelDataScope = () => {
  dataScopeRef.value?.resetFields();
  form.value = { ...initForm };
  openDataScope.value = false;
};

onMounted(() => {
  getList();
});
</script>

// infoq-scaffold-frontend-react-pro/src/pages/system/role/index.tsx
import {
  CheckCircleOutlined,
  DeleteOutlined,
  DownloadOutlined,
  EditOutlined,
  PlusOutlined,
  ReloadOutlined,
  SearchOutlined,
  UserOutlined,
} from '@ant-design/icons';
import {
  Button,
  Card,
  Checkbox,
  Col,
  DatePicker,
  Form,
  Input,
  InputNumber,
  Modal,
  Radio,
  Row,
  Select,
  Space,
  Switch,
  Table,
  Tooltip,
  Tree,
} from 'antd';
import type {ColumnsType} from 'antd/es/table';
import type {DataNode} from 'antd/es/tree';
import type {Dayjs} from 'dayjs';
import {useCallback, useState} from 'react';
import {useNavigate} from '@umijs/max';
import {roleMenuTreeselect, treeselect as menuTreeselect,} from '@/api/system/menu';
import type {MenuTreeOption} from '@/api/system/menu/types';
import {
  addRole,
  changeRoleStatus,
  dataScope,
  delRole,
  deptTreeSelect,
  getRole,
  listRole,
  updateRole,
} from '@/api/system/role';
import type {RoleDeptTree, RoleForm, RoleQuery, RoleVO,} from '@/api/system/role/types';
import Pagination from '@/components/Pagination';
import RightToolbar from '@/components/RightToolbar';
import useInitialLoadEffect from '@/hooks/useInitialLoadEffect';
import useDictOptions from '@/hooks/useDictOptions';
import modal from '@/utils/modal';
import auth from '@/utils/permission';
import {download} from '@/utils/request';
import {addDateRange} from '@/utils/scaffold';

type TreeOption = MenuTreeOption;
type RoleTreeOption = TreeOption | RoleDeptTree['depts'][number];

const initialQuery: RoleQuery = {
  pageNum: 1,
  pageSize: 10,
  roleName: '',
  roleKey: '',
  status: '',
};

const initialForm: RoleForm = {
  roleId: undefined,
  roleName: '',
  roleKey: '',
  roleSort: 1,
  status: '0',
  menuCheckStrictly: true,
  deptCheckStrictly: true,
  remark: '',
  dataScope: '1',
  menuIds: [],
  deptIds: [],
};

const dataScopeOptions = [
  { value: '1', label: '全部数据权限' },
  { value: '2', label: '自定数据权限' },
  { value: '3', label: '本部门数据权限' },
  { value: '4', label: '本部门及以下数据权限' },
  { value: '5', label: '仅本人数据权限' },
  { value: '6', label: '部门及以下或本人数据权限' },
];

const formatRange = (range: [Dayjs, Dayjs] | null) =>
  range
    ? [
        range[0].format('YYYY-MM-DD HH:mm:ss'),
        range[1].format('YYYY-MM-DD HH:mm:ss'),
      ]
    : [];

const toTreeData = (nodes: RoleTreeOption[]): DataNode[] =>
  nodes.map((node) => ({
    key: String(node.id),
    title: node.label,
    children: node.children?.length ? toTreeData(node.children) : undefined,
  }));

export default function RolePage() {
  const navigate = useNavigate();
  const [query, setQuery] = useState<RoleQuery>(initialQuery);
  const [dateRange, setDateRange] = useState<[Dayjs, Dayjs] | null>(null);
  const [loading, setLoading] = useState(false);
  const [showSearch, setShowSearch] = useState(true);
  const [list, setList] = useState<RoleVO[]>([]);
  const [total, setTotal] = useState(0);
  const [selectedIds, setSelectedIds] = useState<Array<string | number>>([]);
  const [dialogOpen, setDialogOpen] = useState(false);
  const [scopeOpen, setScopeOpen] = useState(false);
  const [submitting, setSubmitting] = useState(false);
  const [menuOptions, setMenuOptions] = useState<MenuTreeOption[]>([]);
  const [deptOptions, setDeptOptions] = useState<RoleDeptTree['depts']>([]);
  const [checkedMenuKeys, setCheckedMenuKeys] = useState<
    Array<string | number>
  >([]);
  const [checkedDeptKeys, setCheckedDeptKeys] = useState<
    Array<string | number>
  >([]);
  const [form] = Form.useForm<RoleForm>();
  const editingRoleId = Form.useWatch('roleId', form);
  const menuCheckStrictly =
    Form.useWatch('menuCheckStrictly', form) ?? initialForm.menuCheckStrictly;
  const deptCheckStrictly =
    Form.useWatch('deptCheckStrictly', form) ?? initialForm.deptCheckStrictly;
  const currentDataScope =
    Form.useWatch('dataScope', form) ?? initialForm.dataScope;
  const dict = useDictOptions('sys_normal_disable');

  const loadList = useCallback(
    async (nextQuery: RoleQuery, nextRange: [Dayjs, Dayjs] | null) => {
      setLoading(true);
      try {
        const response = await listRole(
          addDateRange({ ...nextQuery }, formatRange(nextRange)),
        );
        setList(response.rows);
        setTotal(response.total);
      } finally {
        setLoading(false);
      }
    },
    [],
  );

  const loadMenuTree = async (roleId?: string | number) => {
    if (roleId) {
      const response = await roleMenuTreeselect(roleId);
      const data = response.data;
      setMenuOptions(data.menus);
      setCheckedMenuKeys(data.checkedKeys.map(String));
      return;
    }
    const response = await menuTreeselect();
    setMenuOptions(response.data);
    setCheckedMenuKeys([]);
  };

  const loadDeptTree = async (roleId: string | number) => {
    const response = await deptTreeSelect(roleId);
    setDeptOptions(response.data.depts);
    setCheckedDeptKeys(response.data.checkedKeys.map(String));
  };

  useInitialLoadEffect(() => {
    loadList(initialQuery, null);
  }, [loadList], {dedupeKey: 'system-role-initial-list'});

  const columns: ColumnsType<RoleVO> = [
    {
      title: '角色名称',
      dataIndex: 'roleName',
      width: 150,
      align: 'center',
      ellipsis: true,
    },
    {
      title: '权限字符',
      dataIndex: 'roleKey',
      width: 200,
      align: 'center',
      ellipsis: true,
    },
    { title: '显示顺序', dataIndex: 'roleSort', width: 100, align: 'center' },
    {
      title: '状态',
      dataIndex: 'status',
      width: 100,
      align: 'center',
      render: (value: string, record) => (
        <Switch
          checked={value === '0'}
          onChange={async (checked) => {
            const nextStatus = checked ? '0' : '1';
            const confirmed = await modal.confirm(
              `确认要${nextStatus === '0' ? '启用' : '停用'} "${record.roleName}" 角色吗？`,
            );
            if (!confirmed) {
              return;
            }
            await changeRoleStatus(record.roleId, nextStatus);
            modal.msgSuccess('状态修改成功');
            loadList(query, dateRange);
          }}
        />
      ),
    },
    { title: '创建时间', dataIndex: 'createTime', width: 180, align: 'center' },
    {
      title: '操作',
      key: 'action',
      width: 180,
      align: 'center',
      fixed: 'right',
      render: (_, record) => (
        <Space size={4}>
          {record.roleId !== 1 && (
            <>
              {auth.hasPermiOr(['system:role:edit']) && (
                <Tooltip title="修改">
                  <Button
                    type="link"
                    icon={<EditOutlined />}
                    onClick={() => handleEdit(record.roleId)}
                  />
                </Tooltip>
              )}
              {auth.hasPermiOr(['system:role:remove']) && (
                <Tooltip title="删除">
                  <Button
                    danger
                    type="link"
                    icon={<DeleteOutlined />}
                    onClick={() => handleDelete(record.roleId)}
                  />
                </Tooltip>
              )}
              {auth.hasPermiOr(['system:role:edit']) && (
                <Tooltip title="数据权限">
                  <Button
                    type="link"
                    icon={<CheckCircleOutlined />}
                    onClick={() => handleDataScope(record.roleId)}
                  />
                </Tooltip>
              )}
              {auth.hasPermiOr(['system:role:edit']) && (
                <Tooltip title="分配用户">
                  <Button
                    type="link"
                    icon={<UserOutlined />}
                    onClick={() =>
                      navigate(`/system/role-auth/user/${record.roleId}`)
                    }
                  />
                </Tooltip>
              )}
            </>
          )}
        </Space>
      ),
    },
  ];

  const handleEdit = async (roleId?: string | number) => {
    if (!roleId) {
      return;
    }
    const response = await getRole(roleId);
    form.setFieldsValue({ ...initialForm, ...response.data } as RoleForm);
    await loadMenuTree(roleId);
    setDialogOpen(true);
  };

  const handleDelete = async (
    roleId?: string | number | Array<string | number>,
  ) => {
    const target = roleId || selectedIds;
    if (!target || (Array.isArray(target) && target.length === 0)) {
      modal.msgWarning('请选择要删除的角色');
      return;
    }
    const confirmed = await modal.confirm(
      `是否确认删除角色编号为 "${Array.isArray(target) ? target.join(',') : target}" 数据项？`,
    );
    if (!confirmed) {
      return;
    }
    await delRole(target);
    modal.msgSuccess('删除成功');
    setSelectedIds([]);
    loadList(query, dateRange);
  };

  const handleSubmit = async () => {
    const values = await form.validateFields();
    setSubmitting(true);
    try {
      const payload = {
        ...values,
        menuIds: checkedMenuKeys,
      };
      if (values.roleId) {
        await updateRole(payload);
      } else {
        await addRole(payload);
      }
      modal.msgSuccess('操作成功');
      setDialogOpen(false);
      loadList(query, dateRange);
    } finally {
      setSubmitting(false);
    }
  };

  const handleDataScope = async (roleId?: string | number) => {
    if (!roleId) {
      return;
    }
    const response = await getRole(roleId);
    form.setFieldsValue({ ...initialForm, ...response.data } as RoleForm);
    await loadDeptTree(roleId);
    setScopeOpen(true);
  };

  return (
    <Space orientation="vertical" size={12} style={{ width: '100%' }}>
      {showSearch && (
        <Card>
          <Form layout="inline" className="query-form">
            <Row gutter={16} style={{ width: '100%' }}>
              <Col xs={24} md={12} xl={6}>
                <Form.Item
                  label="角色名称"
                  style={{ width: '100%', marginBottom: 12 }}
                >
                  <Input
                    allowClear
                    placeholder="请输入角色名称"
                    value={query.roleName}
                    onChange={(event) =>
                      setQuery((prev) => ({
                        ...prev,
                        roleName: event.target.value,
                      }))
                    }
                    onPressEnter={() => {
                      const next = { ...query, pageNum: 1 };
                      setQuery(next);
                      loadList(next, dateRange);
                    }}
                  />
                </Form.Item>
              </Col>
              <Col xs={24} md={12} xl={6}>
                <Form.Item
                  label="权限字符"
                  style={{ width: '100%', marginBottom: 12 }}
                >
                  <Input
                    allowClear
                    placeholder="请输入权限字符"
                    value={query.roleKey}
                    onChange={(event) =>
                      setQuery((prev) => ({
                        ...prev,
                        roleKey: event.target.value,
                      }))
                    }
                    onPressEnter={() => {
                      const next = { ...query, pageNum: 1 };
                      setQuery(next);
                      loadList(next, dateRange);
                    }}
                  />
                </Form.Item>
              </Col>
              <Col xs={24} md={12} xl={6}>
                <Form.Item
                  label="状态"
                  style={{ width: '100%', marginBottom: 12 }}
                >
                  <Select
                    allowClear
                    style={{ width: '100%' }}
                    placeholder="角色状态"
                    value={query.status || undefined}
                    options={(dict.sys_normal_disable || []).map((item) => ({
                      label: item.label,
                      value: item.value,
                    }))}
                    onChange={(value) =>
                      setQuery((prev) => ({ ...prev, status: value || '' }))
                    }
                  />
                </Form.Item>
              </Col>
              <Col xs={24} md={12} xl={8}>
                <Form.Item
                  label="创建时间"
                  style={{ width: '100%', marginBottom: 12 }}
                >
                  <DatePicker.RangePicker
                    showTime
                    placeholder={['开始日期', '结束日期']}
                    style={{ width: '100%' }}
                    value={dateRange}
                    onChange={(value) =>
                      setDateRange((value as [Dayjs, Dayjs]) || null)
                    }
                  />
                </Form.Item>
              </Col>
              <Col xs={24} md={12} xl={4}>
                <Form.Item style={{ marginBottom: 12 }}>
                  <Space>
                    <Button
                      type="primary"
                      icon={<SearchOutlined />}
                      onClick={() => {
                        const next = { ...query, pageNum: 1 };
                        setQuery(next);
                        loadList(next, dateRange);
                      }}
                    >
                      搜索
                    </Button>
                    <Button
                      icon={<ReloadOutlined />}
                      onClick={() => {
                        setQuery(initialQuery);
                        setDateRange(null);
                        loadList(initialQuery, null);
                      }}
                    >
                      重置
                    </Button>
                  </Space>
                </Form.Item>
              </Col>
            </Row>
          </Form>
        </Card>
      )}

      <Card>
        <div className="table-toolbar">
          <Space wrap className="toolbar-buttons">
            {auth.hasPermiOr(['system:role:add']) && (
              <Button
                className="btn-plain-primary"
                icon={<PlusOutlined />}
                onClick={async () => {
                  form.setFieldsValue(initialForm);
                  await loadMenuTree();
                  setDialogOpen(true);
                }}
              >
                新增
              </Button>
            )}
            {auth.hasPermiOr(['system:role:edit']) && (
              <Button
                icon={<EditOutlined />}
                onClick={() => handleEdit(selectedIds[0])}
                disabled={selectedIds.length !== 1}
                style={{ color: '#67c23a', borderColor: '#b7eb8f' }}
              >
                修改
              </Button>
            )}
            {auth.hasPermiOr(['system:role:remove']) && (
              <Button
                danger
                icon={<DeleteOutlined />}
                onClick={() => handleDelete()}
                disabled={selectedIds.length === 0}
                style={{ borderColor: '#ffccc7' }}
              >
                删除
              </Button>
            )}
            {auth.hasPermiOr(['system:role:export']) && (
              <Button
                icon={<DownloadOutlined />}
                onClick={() =>
                  download(
                    '/system/role/export',
                    addDateRange({ ...query }, formatRange(dateRange)),
                    `role_${Date.now()}.xlsx`,
                  )
                }
                style={{ color: '#e6a23c', borderColor: '#ffd591' }}
              >
                导出
              </Button>
            )}
          </Space>
          <div className="right-toolbar-wrap">
            <RightToolbar
              showSearch={showSearch}
              onShowSearchChange={setShowSearch}
              onQueryTable={() => loadList(query, dateRange)}
            />
          </div>
        </div>

        <Table<RoleVO>
          rowKey="roleId"
          bordered
          scroll={{ x: 980 }}
          loading={loading}
          columns={columns}
          dataSource={list}
          pagination={false}
          rowSelection={{
            selectedRowKeys: selectedIds,
            onChange: (keys) => setSelectedIds(keys as Array<string | number>),
          }}
        />

        <Pagination
          total={total}
          page={query.pageNum}
          limit={query.pageSize}
          onPageChange={({ page, limit }) => {
            const next = { ...query, pageNum: page, pageSize: limit };
            setQuery(next);
            loadList(next, dateRange);
          }}
        />
      </Card>

      <Modal
        width={760}
        open={dialogOpen}
        title={editingRoleId ? '修改角色' : '新增角色'}
        confirmLoading={submitting}
        onCancel={() => setDialogOpen(false)}
        onOk={handleSubmit}
      >
        <Form form={form} layout="vertical" initialValues={initialForm}>
          <Form.Item
            label="角色名称"
            name="roleName"
            rules={[{ required: true, message: '角色名称不能为空' }]}
          >
            <Input />
          </Form.Item>
          <Form.Item
            label="权限字符"
            name="roleKey"
            rules={[{ required: true, message: '权限字符不能为空' }]}
          >
            <Input />
          </Form.Item>
          <Form.Item
            label="角色顺序"
            name="roleSort"
            rules={[{ required: true, message: '角色顺序不能为空' }]}
          >
            <InputNumber min={0} style={{ width: '100%' }} />
          </Form.Item>
          <Form.Item label="状态" name="status">
            <Radio.Group
              options={(dict.sys_normal_disable || []).map((item) => ({
                label: item.label,
                value: item.value,
              }))}
            />
          </Form.Item>
          <Space style={{ marginBottom: 12 }} wrap>
            <Checkbox
              checked={Boolean(menuCheckStrictly)}
              onChange={(event) =>
                form.setFieldValue('menuCheckStrictly', event.target.checked)
              }
            >
              父子联动
            </Checkbox>
          </Space>
          <Tree
            checkable
            defaultExpandAll
            checkStrictly={!menuCheckStrictly}
            treeData={toTreeData(menuOptions)}
            checkedKeys={checkedMenuKeys.map(String)}
            onCheck={(keys) => {
              const nextKeys = Array.isArray(keys) ? keys : keys.checked;
              setCheckedMenuKeys(nextKeys as Array<string | number>);
            }}
          />
          <Form.Item style={{ marginTop: 16 }} label="备注" name="remark">
            <Input.TextArea rows={4} />
          </Form.Item>
        </Form>
      </Modal>

      <Modal
        width={760}
        open={scopeOpen}
        title="分配数据权限"
        onCancel={() => setScopeOpen(false)}
        onOk={async () => {
          const values = await form.validateFields();
          await dataScope({
            ...values,
            deptIds: checkedDeptKeys,
          });
          modal.msgSuccess('修改成功');
          setScopeOpen(false);
          loadList(query, dateRange);
        }}
      >
        <Form form={form} layout="vertical">
          <Form.Item label="角色名称" name="roleName">
            <Input disabled />
          </Form.Item>
          <Form.Item label="权限字符" name="roleKey">
            <Input disabled />
          </Form.Item>
          <Form.Item label="权限范围" name="dataScope">
            <Select options={dataScopeOptions} />
          </Form.Item>
          {currentDataScope === '2' && (
            <>
              <Checkbox
                checked={Boolean(deptCheckStrictly)}
                onChange={(event) =>
                  form.setFieldValue('deptCheckStrictly', event.target.checked)
                }
              >
                父子联动
              </Checkbox>
              <Tree
                checkable
                defaultExpandAll
                checkStrictly={!deptCheckStrictly}
                treeData={toTreeData(deptOptions)}
                checkedKeys={checkedDeptKeys.map(String)}
                onCheck={(keys) => {
                  const nextKeys = Array.isArray(keys) ? keys : keys.checked;
                  setCheckedDeptKeys(nextKeys as Array<string | number>);
                }}
              />
            </>
          )}
        </Form>
      </Modal>
    </Space>
  );
}
