// infoq-scaffold-frontend-vue/src/views/system/dept/index.vue
<template>
  <div class="p-2">
    <transition :enter-active-class="proxy?.animate.searchAnimate.enter" :leave-active-class="proxy?.animate.searchAnimate.leave">
      <div v-show="showSearch" class="mb-[10px]">
        <el-card shadow="hover">
          <el-form ref="queryFormRef" :model="queryParams" :inline="true">
            <el-form-item label="部门名称" prop="deptName">
              <el-input v-model="queryParams.deptName" placeholder="请输入部门名称" clearable @keyup.enter="handleQuery" />
            </el-form-item>
            <el-form-item label="类别编码" prop="deptCategory">
              <el-input v-model="queryParams.deptCategory" placeholder="请输入类别编码" clearable style="width: 240px" @keyup.enter="handleQuery" />
            </el-form-item>
            <el-form-item label="状态" prop="status">
              <el-select v-model="queryParams.status" placeholder="部门状态" clearable>
                <el-option v-for="dict in sys_normal_disable" :key="dict.value" :label="dict.label" :value="dict.value" />
              </el-select>
            </el-form-item>
            <el-form-item>
              <el-button type="primary" icon="Search" @click="handleQuery">搜索</el-button>
              <el-button icon="Refresh" @click="resetQuery">重置</el-button>
            </el-form-item>
          </el-form>
        </el-card>
      </div>
    </transition>

    <el-card shadow="hover">
      <template #header>
        <el-row :gutter="10">
          <el-col :span="1.5">
            <el-button v-hasPermi="['system:dept:add']" type="primary" plain icon="Plus" @click="handleAdd()">新增 </el-button>
          </el-col>
          <el-col :span="1.5">
            <el-button type="info" plain icon="Sort" @click="handleToggleExpandAll">展开/折叠</el-button>
          </el-col>
          <right-toolbar v-model:show-search="showSearch" @query-table="getList"></right-toolbar>
        </el-row>
      </template>

      <el-table
        ref="deptTableRef"
        v-loading="loading"
        :data="deptList"
        row-key="deptId"
        border
        :tree-props="{ children: 'children', hasChildren: 'hasChildren' }"
        :default-expand-all="isExpandAll"
      >
        <el-table-column prop="deptName" label="部门名称" width="260"></el-table-column>
        <el-table-column prop="deptCategory" align="center" label="类别编码" width="200"></el-table-column>
        <el-table-column prop="orderNum" align="center" label="排序" width="200"></el-table-column>
        <el-table-column prop="status" align="center" label="状态" width="100">
          <template #default="scope">
            <dict-tag :options="sys_normal_disable" :value="scope.row.status" />
          </template>
        </el-table-column>
        <el-table-column label="创建时间" align="center" prop="createTime" width="200">
          <template #default="scope">
            <span>{{ proxy.parseTime(scope.row.createTime) }}</span>
          </template>
        </el-table-column>
        <el-table-column fixed="right" align="center" label="操作">
          <template #default="scope">
            <el-tooltip content="修改" placement="top">
              <el-button v-hasPermi="['system:dept:edit']" link type="primary" icon="Edit" @click="handleUpdate(scope.row)" />
            </el-tooltip>
            <el-tooltip content="新增" placement="top">
              <el-button v-hasPermi="['system:dept:add']" link type="primary" icon="Plus" @click="handleAdd(scope.row)" />
            </el-tooltip>
            <el-tooltip content="删除" placement="top">
              <el-button v-hasPermi="['system:dept:remove']" link type="primary" icon="Delete" @click="handleDelete(scope.row)" />
            </el-tooltip>
          </template>
        </el-table-column>
      </el-table>
    </el-card>

    <el-dialog v-model="dialog.visible" :title="dialog.title" destroy-on-close append-to-body width="600px">
      <el-form ref="deptFormRef" :model="form" :rules="rules" label-width="80px">
        <el-row>
          <el-col v-if="form.parentId !== 0" :span="24">
            <el-form-item label="上级部门" prop="parentId">
              <el-tree-select
                v-model="form.parentId"
                :data="deptOptions"
                :props="deptTreeSelectProps"
                value-key="deptId"
                placeholder="选择上级部门"
                check-strictly
              />
            </el-form-item>
          </el-col>
          <el-col :span="12">
            <el-form-item label="部门名称" prop="deptName">
              <el-input v-model="form.deptName" placeholder="请输入部门名称" />
            </el-form-item>
          </el-col>
          <el-col :span="12">
            <el-form-item label="类别编码" prop="deptCategory">
              <el-input v-model="form.deptCategory" placeholder="请输入类别编码" />
            </el-form-item>
          </el-col>
          <el-col :span="12">
            <el-form-item label="显示排序" prop="orderNum">
              <el-input-number v-model="form.orderNum" controls-position="right" :min="0" />
            </el-form-item>
          </el-col>
          <el-col :span="12">
            <el-form-item label="负责人" prop="leader">
              <el-select v-model="form.leader" placeholder="请选择负责人">
                <el-option v-for="item in deptUserList" :key="item.userId" :label="item.userName" :value="item.userId" />
              </el-select>
            </el-form-item>
          </el-col>
          <el-col :span="12">
            <el-form-item label="联系电话" prop="phone">
              <el-input v-model="form.phone" placeholder="请输入联系电话" maxlength="11" />
            </el-form-item>
          </el-col>
          <el-col :span="12">
            <el-form-item label="邮箱" prop="email">
              <el-input v-model="form.email" placeholder="请输入邮箱" maxlength="50" />
            </el-form-item>
          </el-col>
          <el-col :span="12">
            <el-form-item label="部门状态">
              <el-radio-group v-model="form.status">
                <el-radio v-for="dict in sys_normal_disable" :key="dict.value" :value="dict.value">{{ dict.label }}</el-radio>
              </el-radio-group>
            </el-form-item>
          </el-col>
        </el-row>
      </el-form>
      <template #footer>
        <div class="dialog-footer">
          <el-button type="primary" @click="submitForm">确 定</el-button>
          <el-button @click="cancel">取 消</el-button>
        </div>
      </template>
    </el-dialog>
  </div>
</template>

<script setup name="Dept" lang="ts">
import { addDept, delDept, getDept, listDept, listDeptExcludeChild, updateDept } from '@/api/system/dept';
import { DeptForm, DeptQuery, DeptVO } from '@/api/system/dept/types';
import { UserVO } from '@/api/system/user/types';
import { listUserByDeptId } from '@/api/system/user';
import { toDictRefs } from '@/utils/dict';

interface DeptOptionsType {
  deptId: number | string;
  deptName: string;
  children: DeptOptionsType[];
}

const { proxy } = getCurrentInstance() as ComponentInternalInstance;
const { sys_normal_disable } = toDictRefs((proxy?.useDict('sys_normal_disable') ?? {}) as Record<'sys_normal_disable', DictDataOption[]>);

const deptList = ref<DeptVO[]>([]);
const loading = ref(true);
const showSearch = ref(true);
const deptOptions = ref<DeptOptionsType[]>([]);
const isExpandAll = ref(true);
const deptUserList = ref<UserVO[]>([]);
const deptTreeSelectProps = { value: 'deptId', label: 'deptName', children: 'children' } as const;

const dialog = reactive<DialogOption>({
  visible: false,
  title: ''
});

const deptTableRef = ref<ElTableInstance>();
const queryFormRef = ref<ElFormInstance>();
const deptFormRef = ref<ElFormInstance>();

const initFormData: DeptForm = {
  deptId: undefined,
  parentId: undefined,
  deptName: undefined,
  deptCategory: undefined,
  orderNum: 0,
  leader: undefined,
  phone: undefined,
  email: undefined,
  status: '0'
};
const initData: PageData<DeptForm, DeptQuery> = {
  form: { ...initFormData },
  queryParams: {
    pageNum: 1,
    pageSize: 10,
    deptName: undefined,
    deptCategory: undefined,
    status: undefined
  },
  rules: {
    parentId: [{ required: true, message: '上级部门不能为空', trigger: 'blur' }],
    deptName: [{ required: true, message: '部门名称不能为空', trigger: 'blur' }],
    orderNum: [{ required: true, message: '显示排序不能为空', trigger: 'blur' }],
    email: [{ type: 'email', message: '请输入正确的邮箱地址', trigger: ['blur', 'change'] }],
    phone: [{ pattern: /^1[3456789][0-9]\d{8}$/, message: '请输入正确的手机号码', trigger: 'blur' }]
  }
};
const data = reactive<PageData<DeptForm, DeptQuery>>(initData);

const { queryParams, form, rules } = toRefs<PageData<DeptForm, DeptQuery>>(data);

/** 查询菜单列表 */
const getList = async () => {
  loading.value = true;
  const res = await listDept(queryParams.value);
  const data = proxy?.handleTree<DeptVO>(res.data, 'deptId');
  if (data) {
    deptList.value = data;
  }
  loading.value = false;
};

/** 查询当前部门的所有用户 */
async function getDeptAllUser(deptId: number | string | undefined) {
  if (deptId !== null && deptId !== '' && deptId !== undefined) {
    const res = await listUserByDeptId(deptId);
    deptUserList.value = res.data;
  }
}

/** 取消按钮 */
const cancel = () => {
  reset();
  dialog.visible = false;
};
/** 表单重置 */
const reset = () => {
  form.value = { ...initFormData };
  deptFormRef.value?.resetFields();
};

/** 搜索按钮操作 */
const handleQuery = () => {
  getList();
};
/** 重置按钮操作 */
const resetQuery = () => {
  queryFormRef.value?.resetFields();
  handleQuery();
};

/** 展开/折叠操作 */
const handleToggleExpandAll = () => {
  isExpandAll.value = !isExpandAll.value;
  toggleExpandAll(deptList.value, isExpandAll.value);
};
/** 展开/折叠所有 */
const toggleExpandAll = (data: DeptVO[], status: boolean) => {
  data.forEach((item) => {
    deptTableRef.value?.toggleRowExpansion(item, status);
    if (item.children && item.children.length > 0) toggleExpandAll(item.children, status);
  });
};

/** 新增按钮操作 */
const handleAdd = async (row?: DeptVO) => {
  reset();
  const res = await listDept();
  const data = proxy?.handleTree<DeptOptionsType>(res.data, 'deptId');
  if (data) {
    deptOptions.value = data;
    if (row && row.deptId) {
      form.value.parentId = row.deptId;
    }
    dialog.visible = true;
    dialog.title = '添加部门';
  }
};

/** 修改按钮操作 */
const handleUpdate = async (row: DeptVO) => {
  reset();
  //查询当前部门所有用户
  getDeptAllUser(row.deptId);
  const res = await getDept(row.deptId);
  form.value = res.data;
  const response = await listDeptExcludeChild(row.deptId);
  const data = proxy?.handleTree<DeptOptionsType>(response.data, 'deptId');
  if (data) {
    deptOptions.value = data;
    if (data.length === 0) {
      const noResultsOptions: DeptOptionsType = {
        deptId: res.data.parentId,
        deptName: res.data.parentName,
        children: []
      };
      deptOptions.value.push(noResultsOptions);
    }
  }
  dialog.visible = true;
  dialog.title = '修改部门';
};
/** 提交按钮 */
const submitForm = () => {
  deptFormRef.value?.validate(async (valid: boolean) => {
    if (valid) {
      const payload: DeptForm = {
        deptId: form.value.deptId,
        parentId: form.value.parentId,
        deptName: form.value.deptName,
        deptCategory: form.value.deptCategory,
        orderNum: form.value.orderNum,
        leader: form.value.leader,
        phone: form.value.phone,
        email: form.value.email,
        status: form.value.status
      };
      payload.deptId ? await updateDept(payload) : await addDept(payload);
      proxy?.$modal.msgSuccess('操作成功');
      dialog.visible = false;
      await getList();
    }
  });
};
/** 删除按钮操作 */
const handleDelete = async (row: DeptVO) => {
  await proxy?.$modal.confirm('是否确认删除名称为"' + row.deptName + '"的数据项?');
  await delDept(row.deptId);
  await getList();
  proxy?.$modal.msgSuccess('删除成功');
};

onMounted(() => {
  getList();
});
</script>

// infoq-scaffold-frontend-react/src/pages/system/dept/index.tsx
import { useCallback, useEffect, useState } from 'react';
import { DeleteOutlined, EditOutlined, PlusOutlined, ReloadOutlined, SearchOutlined, SortAscendingOutlined } from '@ant-design/icons';
import { Button, Card, Col, Form, Input, InputNumber, Modal, Radio, Row, Select, Space, Table, Tooltip, TreeSelect } from 'antd';
import type { ColumnsType } from 'antd/es/table';
import useDictOptions from '@/hooks/useDictOptions';
import { addDept, delDept, getDept, listDept, listDeptExcludeChild, updateDept } from '@/api/system/dept';
import type { DeptForm, DeptQuery, DeptVO } from '@/api/system/dept/types';
import { listUserByDeptId } from '@/api/system/user';
import type { UserVO } from '@/api/system/user/types';
import RightToolbar from '@/components/RightToolbar';
import DictTag from '@/components/DictTag';
import modal from '@/utils/modal';
import auth from '@/utils/permission';
import { handleTree } from '@/utils/scaffold';

const initialQuery: DeptQuery = {
  pageNum: 1,
  pageSize: 10,
  deptName: '',
  deptCategory: '',
  status: undefined
};

const initialForm: DeptForm = {
  deptId: undefined,
  parentId: undefined,
  deptName: '',
  deptCategory: '',
  orderNum: 0,
  leader: '',
  phone: '',
  email: '',
  status: '0'
};

const toTreeSelectData = (nodes: DeptVO[]) =>
  nodes.map((node) => ({
    value: node.deptId,
    title: node.deptName,
    children: node.children?.length ? toTreeSelectData(node.children) : undefined
  }));

const collectDeptIds = (nodes: DeptVO[]): Array<string | number> =>
  nodes.flatMap((node) => (node.children?.length ? [node.deptId, ...collectDeptIds(node.children)] : []));

const isRootParentId = (value?: string | number | null) => value === undefined || value === null || value === '' || value === 0 || value === '0';

export default function DeptPage() {
  const [query, setQuery] = useState<DeptQuery>(initialQuery);
  const [loading, setLoading] = useState(false);
  const [showSearch, setShowSearch] = useState(true);
  const [list, setList] = useState<DeptVO[]>([]);
  const [deptOptions, setDeptOptions] = useState<DeptVO[]>([]);
  const [deptUsers, setDeptUsers] = useState<UserVO[]>([]);
  const [expandAll, setExpandAll] = useState(true);
  const [expandedRowKeys, setExpandedRowKeys] = useState<Array<string | number>>([]);
  const [dialogOpen, setDialogOpen] = useState(false);
  const [submitting, setSubmitting] = useState(false);
  const [form] = Form.useForm<DeptForm>();
  const deptId = Form.useWatch('deptId', { form, preserve: true });
  const parentId = Form.useWatch('parentId', { form, preserve: true });
  const showParentDept = !deptId || !isRootParentId(parentId);
  const dict = useDictOptions('sys_normal_disable');

  const loadList = useCallback(
    async (nextQuery: DeptQuery) => {
      setLoading(true);
      try {
        const response = await listDept(nextQuery);
        const treeData = handleTree<DeptVO>(response.data, 'deptId');
        setList(treeData);
        setExpandedRowKeys(expandAll ? collectDeptIds(treeData) : []);
      } finally {
        setLoading(false);
      }
    },
    [expandAll]
  );

  const loadDeptOptions = useCallback(async () => {
    const response = await listDept();
    setDeptOptions(handleTree<DeptVO>(response.data, 'deptId'));
  }, []);

  const loadDeptUsers = useCallback(async (deptId?: string | number) => {
    if (deptId === undefined || deptId === null || deptId === '') {
      setDeptUsers([]);
      return;
    }
    const response = await listUserByDeptId(deptId);
    setDeptUsers(response.data);
  }, []);

  useEffect(() => {
    loadList(initialQuery);
    loadDeptOptions();
  }, [loadDeptOptions, loadList]);

  const columns: ColumnsType<DeptVO> = [
    {
      title: '部门名称',
      dataIndex: 'deptName',
      width: 260
    },
    {
      title: '类别编码',
      dataIndex: 'deptCategory',
      width: 200,
      align: 'center'
    },
    {
      title: '排序',
      dataIndex: 'orderNum',
      width: 200,
      align: 'center'
    },
    {
      title: '状态',
      dataIndex: 'status',
      width: 120,
      align: 'center',
      render: (value: string) => <DictTag options={dict.sys_normal_disable || []} value={value} />
    },
    {
      title: '创建时间',
      dataIndex: 'createTime',
      width: 200,
      align: 'center'
    },
    {
      title: '操作',
      key: 'action',
      width: 180,
      align: 'center',
      render: (_, record) => (
        <Space size={4}>
          {auth.hasPermiOr(['system:dept:edit']) && (
            <Tooltip title="修改">
              <Button type="link" icon={<EditOutlined />} onClick={() => handleEdit(record.deptId)} />
            </Tooltip>
          )}
          {auth.hasPermiOr(['system:dept:add']) && (
            <Tooltip title="新增">
              <Button type="link" icon={<PlusOutlined />} onClick={() => handleAdd(record.deptId)} />
            </Tooltip>
          )}
          {auth.hasPermiOr(['system:dept:remove']) && (
            <Tooltip title="删除">
              <Button danger type="link" icon={<DeleteOutlined />} onClick={() => handleDelete(record.deptId, record.deptName)} />
            </Tooltip>
          )}
        </Space>
      )
    }
  ];

  const handleAdd = async (parentId?: string | number) => {
    form.setFieldsValue({
      ...initialForm,
      parentId
    });
    await loadDeptOptions();
    await loadDeptUsers(parentId);
    setDialogOpen(true);
  };

  const handleEdit = async (deptId?: string | number) => {
    if (!deptId) {
      return;
    }
    const detailResponse = await getDept(deptId);
    const detail = { ...initialForm, ...detailResponse.data } as DeptForm;
    const optionsResponse = await listDeptExcludeChild(deptId);
    setDeptOptions(handleTree<DeptVO>(optionsResponse.data, 'deptId'));
    await loadDeptUsers(detail.deptId);
    form.setFieldsValue(detail);
    setDialogOpen(true);
  };

  const handleDelete = async (deptId?: string | number, deptName?: string) => {
    if (!deptId) {
      return;
    }
    const confirmed = await modal.confirm(`是否确认删除名称为 "${deptName || deptId}" 的数据项？`);
    if (!confirmed) {
      return;
    }
    await delDept(deptId);
    modal.msgSuccess('删除成功');
    loadList(query);
  };

  const handleSubmit = async () => {
    const values = await form.validateFields();
    setSubmitting(true);
    try {
      if (values.deptId) {
        await updateDept(values);
      } else {
        await addDept(values);
      }
      modal.msgSuccess('操作成功');
      setDialogOpen(false);
      loadList(query);
      loadDeptOptions();
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <Space orientation="vertical" size={12} style={{ width: '100%' }}>
      {showSearch && (
        <Card>
          <Form layout="inline" className="query-form">
            <Row gutter={16} style={{ width: '100%' }}>
              <Col xs={24} md={12} xl={6}>
                <Form.Item label="部门名称" style={{ width: '100%', marginBottom: 12 }}>
                  <Input
                    allowClear
                    placeholder="请输入部门名称"
                    value={query.deptName}
                    onChange={(event) => setQuery((prev) => ({ ...prev, deptName: event.target.value }))}
                    onPressEnter={() => loadList({ ...query, pageNum: 1 })}
                  />
                </Form.Item>
              </Col>
              <Col xs={24} md={12} xl={6}>
                <Form.Item label="类别编码" style={{ width: '100%', marginBottom: 12 }}>
                  <Input
                    allowClear
                    placeholder="请输入类别编码"
                    value={query.deptCategory}
                    onChange={(event) => setQuery((prev) => ({ ...prev, deptCategory: event.target.value }))}
                    onPressEnter={() => loadList({ ...query, pageNum: 1 })}
                  />
                </Form.Item>
              </Col>
              <Col xs={24} md={12} xl={6}>
                <Form.Item label="状态" style={{ width: '100%', marginBottom: 12 }}>
                  <Select
                    allowClear
                    style={{ width: '100%' }}
                    placeholder="部门状态"
                    value={query.status}
                    options={(dict.sys_normal_disable || []).map((item) => ({ label: item.label, value: item.value }))}
                    onChange={(value) => setQuery((prev) => ({ ...prev, status: value as number | undefined }))}
                  />
                </Form.Item>
              </Col>
              <Col xs={24}>
                <Form.Item style={{ marginBottom: 0 }}>
                  <Space>
                    <Button type="primary" icon={<SearchOutlined />} onClick={() => loadList({ ...query, pageNum: 1 })}>
                      搜索
                    </Button>
                    <Button
                      icon={<ReloadOutlined />}
                      onClick={() => {
                        setQuery(initialQuery);
                        loadList(initialQuery);
                      }}
                    >
                      重置
                    </Button>
                  </Space>
                </Form.Item>
              </Col>
            </Row>
          </Form>
        </Card>
      )}

      <Card>
        <div className="table-toolbar">
          <Space wrap className="toolbar-buttons">
            {auth.hasPermiOr(['system:dept:add']) && (
              <Button className="btn-plain-primary" icon={<PlusOutlined />} onClick={() => handleAdd()}>
                新增
              </Button>
            )}
            <Button
              icon={<SortAscendingOutlined />}
              onClick={() => {
                const nextExpand = !expandAll;
                setExpandAll(nextExpand);
                setExpandedRowKeys(nextExpand ? collectDeptIds(list) : []);
              }}
            >
              展开/折叠
            </Button>
          </Space>
          <div className="right-toolbar-wrap">
            <RightToolbar showSearch={showSearch} onShowSearchChange={setShowSearch} onQueryTable={() => loadList(query)} />
          </div>
        </div>
        <Table<DeptVO>
          rowKey="deptId"
          loading={loading}
          bordered
          columns={columns}
          dataSource={list}
          pagination={false}
          expandable={{
            rowExpandable: (record) => Array.isArray(record.children) && record.children.length > 0,
            expandedRowKeys,
            onExpandedRowsChange: (keys) => setExpandedRowKeys(keys as Array<string | number>)
          }}
        />
      </Card>

      <Modal
        width={600}
        open={dialogOpen}
        transitionName=""
        title={deptId ? '修改部门' : '新增部门'}
        confirmLoading={submitting}
        onCancel={() => setDialogOpen(false)}
        onOk={handleSubmit}
      >
        <Form form={form} layout="vertical" initialValues={initialForm}>
          <Row gutter={16}>
            {showParentDept && (
              <Col span={24}>
                <Form.Item label="上级部门" name="parentId" rules={[{ required: true, message: '上级部门不能为空' }]}>
                  <TreeSelect treeData={toTreeSelectData(deptOptions)} placeholder="选择上级部门" allowClear treeDefaultExpandAll />
                </Form.Item>
              </Col>
            )}
            <Col span={12}>
              <Form.Item label="部门名称" name="deptName" rules={[{ required: true, message: '部门名称不能为空' }]}>
                <Input />
              </Form.Item>
            </Col>
            <Col span={12}>
              <Form.Item label="类别编码" name="deptCategory">
                <Input />
              </Form.Item>
            </Col>
            <Col span={12}>
              <Form.Item label="显示排序" name="orderNum" rules={[{ required: true, message: '显示排序不能为空' }]}>
                <InputNumber min={0} style={{ width: '100%' }} />
              </Form.Item>
            </Col>
            <Col span={12}>
              <Form.Item label="负责人" name="leader">
                <Select
                  allowClear
                  options={deptUsers.map((item) => ({ label: item.userName, value: item.userId }))}
                  onOpenChange={(open) => {
                    if (open) {
                      loadDeptUsers(isRootParentId(parentId) ? deptId : parentId);
                    }
                  }}
                />
              </Form.Item>
            </Col>
            <Col span={12}>
              <Form.Item label="联系电话" name="phone" rules={[{ pattern: /^1[3456789][0-9]\d{8}$/, message: '请输入正确的手机号码' }]}>
                <Input />
              </Form.Item>
            </Col>
            <Col span={12}>
              <Form.Item label="邮箱" name="email" rules={[{ type: 'email', message: '请输入正确的邮箱地址' }]}>
                <Input />
              </Form.Item>
            </Col>
            <Col span={12}>
              <Form.Item label="部门状态" name="status">
                <Radio.Group options={(dict.sys_normal_disable || []).map((item) => ({ label: item.label, value: item.value }))} />
              </Form.Item>
            </Col>
          </Row>
        </Form>
      </Modal>
    </Space>
  );
}
